User.create(username: "ghostskwad", password: "1234")

Character.create(level: 54, klass: "Caster", health: 2745, constitution: 47, strength: 27, dexterity: 78, intelligence: 150)
Equipment.create(name: "Crown of the Three", slot: "head", modifier_type: "intelligence", modifier_value: 87)
Equipment.create(name: "Cloak of the Three", slot: "body", modifier_type: "constitution", modifier_value: 15)
Equipment.create(name: "Divine Khakis", slot: "legs", modifier_type: "constitution", modifier_value: 5)
Equipment.create(name: "Blessed Boots", slot: "feet", modifier_type: "constitution", modifier_value: 10)
Equipment.create(name: "Staff of the Three", slot: "main-hand", modifier_type: "intelligence", modifier_value: 100)
EquipmentSlot.create(equipment_id: 1, wearer_type: "Character", wearer_id: 1)
EquipmentSlot.create(equipment_id: 2, wearer_type: "Character", wearer_id: 1)
EquipmentSlot.create(equipment_id: 3, wearer_type: "Character", wearer_id: 1)
EquipmentSlot.create(equipment_id: 4, wearer_type: "Character", wearer_id: 1)
EquipmentSlot.create(equipment_id: 5, wearer_type: "Character", wearer_id: 1)
Spell.create(name: "Heal", value: 100, flavor_text: "Recovers health to the target")
Spell.create(name: "Singe", value: 75, flavor_text: "Deals fire damage to the target")
Spell.create(name: "Glacier", value: 75, flavor_text: "Deals ice to the target")
Spell.create(name: "Miasma", value: 25, flavor_text: "Poisons the target")
Spell.create(name: "Holy", value: 100000, flavor_text: "Devine Judgement!")
SpellSlot.create(spell_id: 1, caster_type: "Character", caster_id: 1)
SpellSlot.create(spell_id: 2, caster_type: "Character", caster_id: 1)
SpellSlot.create(spell_id: 3, caster_type: "Character", caster_id: 1)
SpellSlot.create(spell_id: 4, caster_type: "Character", caster_id: 1)
SpellSlot.create(spell_id: 5, caster_type: "Character", caster_id: 1)



Character.create(name: "Decker", pronoun: "he", level: 72, klass: "Paladin", health: 8980, constitution: 85, strength: 83, dexterity: 58, intelligence: 48, player_id: 1)
Equipment.create(name: "Godrick's Helm", slot: "head", modifier_type: "constitution", modifier_value: 8)
Equipment.create(name: "Godrick's Chestplate", slot: "body", modifier_type: "constitution", modifier_value: 15)
Equipment.create(name: "Godrick's Tights", slot: "legs", modifier_type: "constitution", modifier_value: 5)
Equipment.create(name: "Godrick's Thighboots", slot: "feet", modifier_type: "constitution", modifier_value: 10)
Equipment.create(name: "Shield of the Crucible", slot: "off-hand", modifier_type: "constitution", modifier_value: 25)
Equipment.create(name: "Crucible Longsword", slot: "main-hand", modifier_type: "strength", modifier_value: 29)
EquipmentSlot.create(equipment_id: 6, wearer_type: "Character", wearer_id: 2)
EquipmentSlot.create(equipment_id: 7, wearer_type: "Character", wearer_id: 2)
EquipmentSlot.create(equipment_id: 8, wearer_type: "Character", wearer_id: 2)
EquipmentSlot.create(equipment_id: 9, wearer_type: "Character", wearer_id: 2)
EquipmentSlot.create(equipment_id: 10, wearer_type: "Character", wearer_id: 2)
EquipmentSlot.create(equipment_id: 11, wearer_type: "Character", wearer_id: 2)
Spell.create(name: "Smite", value: 1500, flavor_text: "Summon's a holy judgement from the heavens" )
SpellSlot.create(spell_id: 6, caster_type: "Character", caster_id: 2)

Enemy.create(name: "The Rank", level: 93, health: 16000, constitution: 400, strength: 136, dexterity: 97, intelligence: 3)

Enemy.create(name: "The Old One", level: ??, health: 27000, constitution: 358, strength: 113, dexterity: 99, intelligence: 113)
Equipment.create(name: "Worn Hood", slot: "head", modifier_type: "constitution", modifier_value: 1)
Equipment.create(name: "Bone Plate", slot: "body", modifier_type: "constitution", modifier_value: 5)
Equipment.create(name: "Worn Pants", slot: "legs", modifier_type: "constitution", modifier_value: 2)
Equipment.create(name: "Bone Thighboots", slot: "feet", modifier_type: "constitution", modifier_value: 4)
Equipment.create(name: "The Reaper", slot: "main-hand", modifier_type: "strength", modifier_value: 20)
EquipmentSlot.create(equipment_id: 12, wearer_type: "Enemy", wearer_id: 2)
EquipmentSlot.create(equipment_id: 13, wearer_type: "Enemy", wearer_id: 2)
EquipmentSlot.create(equipment_id: 14, wearer_type: "Enemy", wearer_id: 2)
EquipmentSlot.create(equipment_id: 15, wearer_type: "Enemy", wearer_id: 2)
EquipmentSlot.create(equipment_id: 16, wearer_type: "Enemy", wearer_id: 2)
Spell.create(name: "Corruption", value: 50, flavor_text: "Corrupts the flesh, gradually rotting it.")
Spell.create(name: "Sunder", value: 1500 , flavor_text: "Summons a dark dudgement from the pits of hell.")
SpellSlot.create(spell_id: 7, caster_type: "Enemy", caster_id: 2)
SpellSlot.create(spell_id: 8, caster_type: "Enemy", caster_id: 2)

State.create(user_id: 1, character_id: 1, boss1_type: "Enemy", boss1_id: 1, boss2_type: "Enemy", boss2_id: 2)

Story.create(paragraph: %Q(Not many know the history of what happened that day, but those who do say that the air tasted of metal the following morning. Others say that there was an eerie silence about; the roosters did not crow, and not even a whisper of air blew to rustle the trees. Only one thing is certain. Death visited Astaphara that night.))
Story.create(paragraph: %Q(I have received an account of the final hours of the most prosperous country this world has ever seen. What happened to its subjects was swift and, dare I say, merciful, though not bereft of a gruesomeness befitting a waking nightmare. I was told that a dark, translucent sphere engulfed the castle in the capital city, pulsated twice, and then sent out a silent shockwave. It spread as far as the eye could see, seeming to cut through any audibility until all else was silent. But, by my account, it was not a natural silence. It rippled through the eardrums, inaudibly, but palpable. Ten seconds is the count I was given. Ten seconds of that palpable silence, until the eeriness of what happened next…))
Story.create(paragraph: %Q(“Bodies liquified and splashed backwards onto the concrete. Not all at once. But…” ${name} sighed as ${pronoun} recounted this. I could see tears on the brim of their eyes, but ${pronoun} refused to let them fall. “Like a… like a… like a symphony. We couldn't hear a thing, but they were dying to a symphony. It was devoid of sound, but I can't explain it any other way. One, sometimes two a time, but never more. They would splatter backward from where they stood. I saw kids crying for their parents, and the other way around, unable to be heard, just awaiting their turn. Until we were all that was left standing, and the cobblestone roads had turned into a literal river of blood.”))
Story.create(paragraph: %Q(The sphere pulsated one last time, and with it came another shockwave. Though this time it didn’t emanate from the sphere, but rather off in the distance, returning to it. And with it came the sound returned. The sound of silence. A world devoid of life. And they knew. In one fell swoop, Astaphara had fallen.))
Story.create(paragraph: %Q(And in the city streets, there remained only two.))
Story.create(paragraph: %Q(“Do you think they’re ok?”))
Story.create(paragraph: %Q(${name} knew ${pronoun} wouldn’t get an answer. Decker was not much the talker. They had left to adventure together a little over two years ago. Him the divine paladin the Three Gods had promised and ${name}, the caster that they had Named. And in that time, he had said little more to his sibling than “Make sure your gear is ready” whenever they flung themselves into a battle. And though ${name} would never admit it, ${pronoun} had grown so starved for company that they’d resorted to dialoguing conversation between them whenever he wasn’t present. And, also in this time, Decker had said that he loved ${pronoun} exactly one time. That was exactly one month ago when he declared that they needed to return home.))
Story.create(paragraph: %Q(“I had a vision. Our family is in danger. Make sure your gear is ready…. And ${name}. I love you!”))
Story.create(paragraph: %Q(A month-long journey home, and this is what they had returned to. And while ${name} stood there clutching onto Decker’s cape, hoping for, but not anticipating a response, and dreading the journey up to the castle, their home, Decker stood more alert. He was aware of what was happening. And had he not been, ${name} would be dead, for in a split second, the blood that had blanketed the streets had amassed itself into a menacing figure, and when it had lashed out in their direction, it was Decker who had pushed ${pronoun} out of the way and had shielded the blow!))
# Story.create(paragraph: %Q())
# Story.create(paragraph: %Q())
# Story.create(paragraph: %Q())
# Story.create(paragraph: %Q())
# Story.create(paragraph: %Q())
# Story.create(paragraph: %Q())
# Story.create(paragraph: %Q())
# Story.create(paragraph: %Q())