User.create(username: "ghostskwad", password: "1234")

Character.create(level: 54, klass: "Caster", health: 2745, constitution: 47, strength: 27, dexterity: 78, intelligence: 150)
Equipment.create(name: "Crown of the Three", slot: "head", modifier_type: "intelligence", modifier_value: 87)
Equipment.create(name: "Cloak of the Three", slot: "body", modifier_type: "constitution", modifier_value: 15)
Equipment.create(name: "Divine Khakis", slot: "legs", modifier_type: "constitution", modifier_value: 5)
Equipment.create(name: "Blessed Boots", slot: "feet", modifier_type: "constitution", modifier_value: 10)
Equipment.create(name: "Staff of the Three", slot: "main-hand", modifier_type: "intelligence", modifier_value: 100)
EquipmentSlot.create(equipment_id: 1, wearer_type: "Character", wearer_id: 1)
EquipmentSlot.create(equipment_id: 2, wearer_type: "Character", wearer_id: 1)
EquipmentSlot.create(equipment_id: 3, wearer_type: "Character", wearer_id: 1)
EquipmentSlot.create(equipment_id: 4, wearer_type: "Character", wearer_id: 1)
EquipmentSlot.create(equipment_id: 5, wearer_type: "Character", wearer_id: 1)
Spell.create(name: "Heal", value: 100, flavor_text: "Recovers health to the target")
Spell.create(name: "Singe", value: 75, flavor_text: "Deals fire damage to the target")
Spell.create(name: "Glacier", value: 75, flavor_text: "Deals ice to the target")
Spell.create(name: "Miasma", value: 25, flavor_text: "Poisons the target")
Spell.create(name: "Holy", value: 100000, flavor_text: "Devine Judgement!")
SpellSlot.create(spell_id: 1, caster_type: "Character", caster_id: 1)
SpellSlot.create(spell_id: 2, caster_type: "Character", caster_id: 1)
SpellSlot.create(spell_id: 3, caster_type: "Character", caster_id: 1)
SpellSlot.create(spell_id: 4, caster_type: "Character", caster_id: 1)
SpellSlot.create(spell_id: 5, caster_type: "Character", caster_id: 1)



Character.create(name: "Decker", pronoun: "he", level: 72, klass: "Paladin", health: 8980, constitution: 85, strength: 83, dexterity: 58, intelligence: 48, player_id: 1)
Equipment.create(name: "Godrick's Helm", slot: "head", modifier_type: "constitution", modifier_value: 8)
Equipment.create(name: "Godrick's Chestplate", slot: "body", modifier_type: "constitution", modifier_value: 15)
Equipment.create(name: "Godrick's Tights", slot: "legs", modifier_type: "constitution", modifier_value: 5)
Equipment.create(name: "Godrick's Thighboots", slot: "feet", modifier_type: "constitution", modifier_value: 10)
Equipment.create(name: "Shield of the Crucible", slot: "off-hand", modifier_type: "constitution", modifier_value: 25)
Equipment.create(name: "Crucible Longsword", slot: "main-hand", modifier_type: "strength", modifier_value: 29)
EquipmentSlot.create(equipment_id: 6, wearer_type: "Character", wearer_id: 2)
EquipmentSlot.create(equipment_id: 7, wearer_type: "Character", wearer_id: 2)
EquipmentSlot.create(equipment_id: 8, wearer_type: "Character", wearer_id: 2)
EquipmentSlot.create(equipment_id: 9, wearer_type: "Character", wearer_id: 2)
EquipmentSlot.create(equipment_id: 10, wearer_type: "Character", wearer_id: 2)
EquipmentSlot.create(equipment_id: 11, wearer_type: "Character", wearer_id: 2)
Spell.create(name: "Smite", value: 1500, flavor_text: "Summon's a holy judgement from the heavens" )
SpellSlot.create(spell_id: 6, caster_type: "Character", caster_id: 2)

Enemy.create(name: "The Rank", level: 93, health: 16000, constitution: 400, strength: 136, dexterity: 97, intelligence: 3)

Enemy.create(name: "The Old One", level: ??, health: 27000, constitution: 358, strength: 113, dexterity: 99, intelligence: 113)
Equipment.create(name: "Worn Hood", slot: "head", modifier_type: "constitution", modifier_value: 1)
Equipment.create(name: "Bone Plate", slot: "body", modifier_type: "constitution", modifier_value: 5)
Equipment.create(name: "Worn Pants", slot: "legs", modifier_type: "constitution", modifier_value: 2)
Equipment.create(name: "Bone Thighboots", slot: "feet", modifier_type: "constitution", modifier_value: 4)
Equipment.create(name: "The Reaper", slot: "main-hand", modifier_type: "strength", modifier_value: 20)
EquipmentSlot.create(equipment_id: 12, wearer_type: "Enemy", wearer_id: 2)
EquipmentSlot.create(equipment_id: 13, wearer_type: "Enemy", wearer_id: 2)
EquipmentSlot.create(equipment_id: 14, wearer_type: "Enemy", wearer_id: 2)
EquipmentSlot.create(equipment_id: 15, wearer_type: "Enemy", wearer_id: 2)
EquipmentSlot.create(equipment_id: 16, wearer_type: "Enemy", wearer_id: 2)
Spell.create(name: "Corruption", value: 50, flavor_text: "Corrupts the flesh, gradually rotting it.")
Spell.create(name: "Sunder", value: 1500 , flavor_text: "Summons a dark dudgement from the pits of hell.")
SpellSlot.create(spell_id: 7, caster_type: "Enemy", caster_id: 2)
SpellSlot.create(spell_id: 8, caster_type: "Enemy", caster_id: 2)

State.create(user_id: 1, character_id: 1, boss1_type: "Enemy", boss1_id: 1, boss2_type: "Enemy", boss2_id: 2)

Scene.create(scene: 1)
Scene.create(scene: 2)
Scene.create(scene: 3)

Story.create(paragraph: %Q(Not many know the history of what happened that day, but those who do say that the air tasted of metal the following morning. Others say that there was an eerie silence about; the roosters did not crow, and not even a whisper of air blew to rustle the trees. Only one thing is certain. Death visited Astaphara that night.), scene_id: 1)
Story.create(paragraph: %Q(I have received an account of the final hours of the most prosperous country this world has ever seen. What happened to its subjects was swift and, dare I say, merciful, though not bereft of a gruesomeness befitting a waking nightmare. I was told that a dark, translucent sphere engulfed the castle in the capital city, pulsated twice, and then sent out a silent shockwave. It spread as far as the eye could see, seeming to cut through any audibility until all else was silent. But, by my account, it was not a natural silence. It rippled through the eardrums, inaudibly, but palpable. Ten seconds is the count I was given. Ten seconds of that palpable silence, until the eeriness of what happened next…), scene_id: 1)
Story.create(paragraph: %Q(“Bodies liquified and splashed backwards onto the concrete. Not all at once. But…” Blake sighed as he recounted this. I could see tears on the brim of his eyes, but he refused to let them fall. “Like a… like a… like a symphony. We couldn't hear a thing, but they were dying to a symphony. It was devoid of sound, but I can't explain it any other way. One, sometimes two a time, but never more. They would splatter backward from where they stood. I saw kids crying for their parents, and the other way around, unable to be heard, just awaiting their turn. Until we were all that was left standing, and the cobblestone roads had turned into a literal river of blood.”), scene_id: 1)
Story.create(paragraph: %Q(The sphere pulsated one last time, and with it came another shockwave. Though this time it didn’t emanate from the sphere, but rather off in the distance, returning to it. And with it came the sound returned. The sound of silence. A world devoid of life. And they knew. In one fell swoop, Astaphara had fallen.), scene_id: 1)
Story.create(paragraph: %Q(And in the city streets, there remained only two.), scene_id: 1)
Story.create(paragraph: %Q(“Do you think they’re ok?”), scene_id: 1)
Story.create(paragraph: %Q(Blake knew he wouldn’t get an answer. Decker was not much the talker. They had left to adventure together a little over two years ago. Him the divine paladin the Three Gods had promised and Blake, the caster that they had Named. And in that time, he had said little more to his sibling than “Make sure your gear is ready” whenever they flung themselves into a battle. And though Blake would never admit it, he had grown so starved for company that they’d resorted to dialoguing conversation between them whenever he wasn’t present. And, also in this time, Decker had said that he loved him exactly one time. That was exactly one month ago when he declared that they needed to return home.), scene_id: 1)
Story.create(paragraph: %Q(“I had a vision. Our family is in danger. Make sure your gear is ready…. And Blake. I love you!”), scene_id: 1)
Story.create(paragraph: %Q(A month-long journey home, and this is what they had returned to. And while Blake stood there clutching onto Decker’s cape, hoping for, but not anticipating a response, and dreading the journey up to the castle, their home, Decker stood more alert. He was aware of what was happening. And had he not been, Blake would be dead, for in a split second, the blood that had blanketed the streets had amassed itself into a menacing figure, and when it had lashed out in their direction, it was Decker who had pushed him out of the way and had shielded the blow!), scene_id: 1)
Story.create(paragraph: %Q(“Let’s go!”), scene_id: 2)
Story.create(paragraph: %Q(They had just defeated some strange sort of blood creature, and that is the most that he could say. No matter how dire the situation, Decker was always himself.), scene_id: 2)
Story.create(paragraph: %Q(They walked through the streets of the capital city, each trying desperately to stave off their own sense of dread. This was their home: They walked past the stables where their horses were kept; the barracks where they had received their survival and combat training; Decker passed the home of the nan who had taken his virginity; Blake reflected on the fields where he would play with his friends. But all of that was gone now. All that remained were the blood-soaked buildings of those who once attended them.), scene_id: 2)
Story.create(paragraph: %Q(Before too long, they arrived at the castle gates. The place they had once looked upon as a beacon of hope, prosperity and safety now had an omen about it. Decker instinctively put his hand up against the dark sphere that encircled their home, and it faded away, almost like it were never there. Then he did something…unexpected. He took Blake’s hand and lead him through the grounds and into the castle.), scene_id: 2)
Story.create(paragraph: %Q(Yes, they had not been home in over two years, but this did not feel like home at all. It was just a building. A decadent building crafted of the finest stones, woods and fabrics. The finest art lining its halls and decorating its rooms. But it lacked the love that was present before. The laughter that used to fill its halls and the smiles that would greet you around every corner. And the warmth. There was no warmth here.), scene_id: 2)
Story.create(paragraph: %Q(“Decker.”), scene_id: 2)
Story.create(paragraph: %Q(But there was no response. Decker just pulledhim along through the cold, dimly lit and unwelcoming passageways.), scene_id: 2)
Story.create(paragraph: %Q(“Decker.”), scene_id: 2)
Story.create(paragraph: %Q(Still no response.), scene_id: 2)
Story.create(paragraph: %Q(“DECKER!” Blake yelled, pulling his hand away from Decker and refusing to be pulled along any further.), scene_id: 2)
Story.create(paragraph: %Q(“We have to keep moving.”), scene_id: 2)
Story.create(paragraph: %Q(“No! You need to tell me what is going on!” Blake demanded as tears began flooding his eyes. “They’re not ok. And I know you know. You always know, but you never tell me anything. These last couple of years. It wasn’t an adventure. Everywhere that we went and everything that we did. You planned it out. You’re my brother. And I love you, so I never questioned you. I fed into how vague you always claim your visions are. But you rushed me out of here two years ago claiming that it was dad’s decision for us to see the world. To live…. We almost died every other fucking day! And mom always said every corner of this place would be brimming with the warmth of her love. It’s not Decker! It's cold and I hate it here now, and it looks like no one has been here years. What is going on!?”), scene_id: 2)
Story.create(paragraph: %Q(Blake was too lost in his own despair to realize it at the time, but, possibly for the first time in his nineteen years, Decker shed a tear.), scene_id: 2)
Story.create(paragraph: %Q(“They all died the night that we left. Mom… Dad… Alyra… Gabriel… Tannis… Opal… Trenton… Sylas… Xanna… Paxton… The twins. I remind myself every day not to forget.”), scene_id: 2)
Story.create(paragraph: %Q(Blake was confused.), scene_id: 2)
Story.create(paragraph: %Q(“How did we survive? Why don’t I remember any of this? If this happened years ago, what was that outside?”), scene_id: 2)
Story.create(paragraph: %Q(“We both only survived because of The Blessing of the Three. And as for the rest. I don’t know. And that is the truth. What I do know is that this darkness must be stopped, or what happened outside will happen to the rest of the world. And you are the only one who can stop it. Everything that we’ve done, everywhere that we’ve been, every artifact we’ve obtained. It was all so that we could get back here in time to stop this evil.”), scene_id: 2)
Story.create(paragraph: %Q(In that moment, Blake, who had since fallen to his knees and was weeping on the floor, dried his eyes, strengthened his resolve, rose to his feet and took his brother’s hand.), scene_id: 2)
Story.create(paragraph: %Q(Decker led the way, but Blake knew exactly where they were headed. And it wasn’t a long trek. The throne room was located at the center of the castle.  And as they neared it, this overwhelming feeling of despair creeped slowly in, growing more intense the closer they were, nesting itself inside of their bones. By the time they had reached the massive double doors that lead into the throne room, it had become a weight so heavy that it was a struggle just to stay up right.), scene_id: 2)
Story.create(paragraph: %Q(Just as Blake felt like he could no longer move, Decker mumbled something under his breath, and the feeling was lifted, and instead gave way to a voice. A voice shallow and snake-like, inside their heads.), scene_id: 2)
Story.create(paragraph: %Q(Come…in), scene_id: 2)
Story.create(paragraph: %Q(Almost without will, they did as they were told. They pushed the heavy doors open and entered the throne room. And it was nothing like they remembered it. It looked more like a crypt, bones comprising the entire makeup of the room. The only familiarity was the location of the throne, though it and who sat upon it were strangers to the eye. The throne itself was constructed entirely of bone, and the man sitting upon it, was no human, but a skeletal corps, of a strong stature, not much unlike Decker’s, with a face entirely lacking flesh and gaunt, rotting flesh the rest throughout.), scene_id: 2)
Story.create(paragraph: %Q(You have returned…to me. Shed that awful divine stench and make me whole!), scene_id: 2)
Story.create(paragraph: %Q(“I won’t,” said Decker.), scene_id: 2)
Story.create(paragraph: %Q(You mean to defy me…again?), scene_id: 2)
Story.create(paragraph: %Q(Blake felt as though he had been stabbed. What—), scene_id: 2)
Story.create(paragraph: %Q(“What does he mean ‘again’!?”), scene_id: 2)
Story.create(paragraph: %Q(Decker did not respond), scene_id: 2)
Story.create(paragraph: %Q(“Decker! What does he mean?”), scene_id: 2)
Story.create(paragraph: %Q(“It’s not what you think”), scene_id: 2)
Story.create(paragraph: %Q(It’s exactly what he…thinks! All your loved ones. Gone. Thanks to…him), scene_id: 2)
Story.create(paragraph: %Q(“Liar!” Decker was overcome with tears.  “I tried to save them.”), scene_id: 2)
Story.create(paragraph: %Q(Blake had never seen him this way before. Decker was a stalwart protector. He couldn’t even recount a time when he had even seen him crack a smile. Yet here he was, on his knees, sobbing.), scene_id: 2)
Story.create(paragraph: %Q(You killed them), scene_id: 2)
Story.create(paragraph: %Q(“No” Decker wept.), scene_id: 2)
Story.create(paragraph: %Q(Yes!), scene_id: 2)
Story.create(paragraph: %Q(Blake couldn’t stand watching ${pronoun} brother in this way, any longer. He cast a lightening spell and attacked the usurper.), scene_id: 2)
# Story.create(paragraph: %Q())
# Story.create(paragraph: %Q())
# Story.create(paragraph: %Q())